"use client";

import Header from "@/components/common/header/Header";
import "./globals.css";
import Footer from "@/components/common/footer/Footer";
import { usePathname } from "next/navigation";

import localFont from "next/font/local";
const poppins = localFont({
  src: "../app/fonts/Poppins-Regular.ttf",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function MainLayout({ children }) {
  const pathname = usePathname();
  return (
    <>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
